modLoader="javafml"
loaderVersion="[28,)"
logoFile="logo.png" #optional
issueTrackerURL="https://github.com/minecraftabnormals/Berry-Good/issues"
license="https://github.com/minecraftabnormals/Berry-Good/blob/master/LICENSE.txt"

[[mods]]
    modId="berry_good"
    namespace="berry_good"
    version="${file.jarVersion}"
    displayName="Berry Good"
    authors="SmellyModder Cameron, Five, Bagel"
    description='''Makes sweet berries less annoying to eat and adds more berry related content'''
    displayURL=""

	[[dependencies.berry_good]]
	    modId="forge"
	    mandatory=true
	    versionRange="[32.0.88,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.berry_good]]
	    modId="abnormals_core"
	    mandatory=true
	    versionRange="[2.1.0,)"
	    ordering="AFTER"
	    side="BOTH"
	
	[[dependencies.berry_good]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.16.1]"
	    ordering="NONE"
	    side="BOTH"
