modLoader="javafml"
loaderVersion="[28,)"
logoFile="logo.png" #optional
issueTrackerURL="https://github.com/minecraftabnormals/Berry-Good/issues"

[[mods]]
    modId="berry_good"
    namespace="berry_good"
    version="2.0"
    displayName="Berry Good"
    authors="SmellyModder, Cameron, Five"
    description='''Makes sweet berries less annoying to eat and adds more berry related content'''
    displayURL=""
    [[dependencies.berry_good]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"
        side="BOTH"