modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/berry-good/issues"
license = "https://github.com/team-abnormals/berry-good/blob/main/LICENSE.txt"

[[mods]]
    modId = "berry_good"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "berry_good:sweet_berry_pips"
    authors = "Team Abnormals"
    credits = "SmellyModder, Cameron, five, bageldotjpg"
    displayName = "Berry Good"
    description = '''
    Makes sweet berries less annoying to eat and adds more berry related content
    '''

[[dependencies.berry_good]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.berry_good]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.berry_good]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.1.1,)"
    ordering = "AFTER"
    side = "BOTH"